language: go
dist: trusty
sudo: false

go:
  - 1.6.4
  - 1.7.5

addons:
  apt:
    packages:
    - tmux

install:
  - tmux -V
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go get -u github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/goimports

script:
  - go test -v
  - diff <(goimports -d .) <(printf "")

after_success:
  - diff <(golint ./...) <(printf "")
